from django.urls import path
from . import views

from .views import BookingList,BookingView, RoomListView
urlpatterns = [
  path('',views.index, name='index'),
  path('update_profile/',views.update_profile , name= 'update_profile'),
  path('price/',views.price, name ='price'),
  path('contact/',views.contact, name= 'contact'),
  path('destinations/',views.destinations, name= 'destinations'),
  path('offers/',views.offers, name= 'offers'),
  path('stay-without-programe/',views.Programme, name= 'programme'),
  path('almyra/',views.almyra, name= 'almyra'),
  path('how-we-work/',views.we, name= 'how-we-work'),
  path('Siwa/',views.Siwa, name= 'Siwa'),
  path('Helwan/',views.Helwan, name= 'Helwan'),
  path('Dream_Lodge_Siwa/',views.D1, name= 'Dream_Lodge_Siwa'),
  path('Siwa_Shali_Resort/',views.D2, name= 'Siwa_Shali_Resort'),
  path('Sinia/',views.Sinia, name= 'Sinia'),
  path('Savoy_Sharm/',views.D3, name= 'Savoy_Sharm'),
  path('Mövenpick_Resort_Aswan/',views.D4, name= 'Mövenpick_Resort_Aswan'),
  # path('amanwella/',views.D4, name= 'amanwella'),
  path('Eco_Nubia/',views.D5, name= 'Eco_Nubia'),
  path('amal-tamara/',views.D6, name= 'amal-tamara'),
  path('Baron_Palms_Resort/',views.D7, name= 'Baron_Palms_Resort'),
  path('Aswan/',views.Aswan, name= 'Aswan'),
  path('forgetpassword/',views.forgetpass , name= 'forgetpass'),
  # path('signup/',views.signup , name= 'signup'),
  path('profile/',views.Profile , name= 'profile'),
  path('P1/',views.P1 , name= 'P1'),
  path('room_list/',RoomListView.as_view() , name= 'room_list'),
  path('booking_list/',BookingList.as_view() , name= 'booking_list'),
  path('book/',BookingView.as_view() , name= 'BookingView'),
  path('cart/',views.cart  , name= 'cart'),
  path('carts/',views.carts  , name= 'carts'),
  path('single_pro/',views.single_pro  , name= 'single_pro'),
  path('checkout/',views.checkout  , name= 'checkout'),
  # path('room/',RoomDetailView.as_view() , name= 'RoomDetailView'),
]