# Generated by Django 5.0.4 on 2024-06-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CareType',
            fields=[
                ('Care_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Care', models.CharField(choices=[('تقوية الأعصاب', 'تقوية الأعصاب'), ('الإسترخاء', 'الإسترخاء'), ('الدفن في الرمال', 'الدفن في الرمال'), ('المياة المعدنية', 'المياة المعدنية'), ('الأبار و العيون ', 'الأبار و العيون ')], max_length=50, verbose_name='الرعاية')),
            ],
            options={
                'verbose_name': 'CareType',
                'verbose_name_plural': 'CareTypes',
                'db_table': 'Care_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComplainsComments',
            fields=[
                ('complains_comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=8, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ComplainsComment',
                'verbose_name_plural': 'ComplainsComments',
                'db_table': 'complains_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('disease_id', models.IntegerField(primary_key=True, serialize=False)),
                ('disease', models.CharField(choices=[('الضعف و الوهن', 'الضعف و الوهن'), ('التورم', 'التورم'), ('ألم المفاصل', 'ألم المفاصل'), ('الروماتيزم', 'الروماتيزم'), ('الصدفية', 'الصدفية'), ('عرق النسا', 'عرق النسا'), ('التهابات الجلدية', 'التهابات الجلدية'), ('ألم الظهر', 'ألم الظهر'), ('الروماتويد', 'الروماتويد'), ('الإرتشاح المفصلي', 'الإرتشاح المفصلي')], max_length=50, verbose_name='المرض')),
            ],
            options={
                'verbose_name': 'Disease',
                'verbose_name_plural': 'Diseases',
                'db_table': 'diseases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('information', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'Hotels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('offer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=6, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('period', models.IntegerField(blank=True, null=True)),
                ('count_person', models.CharField(blank=True, max_length=50, null=True)),
                ('count_room', models.IntegerField(blank=True, null=True)),
                ('information', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffersBooking',
            fields=[
                ('offer_book_id', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_date', models.DateField()),
                ('book_state', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'OffersBooking',
                'verbose_name_plural': 'OffersBookings',
                'db_table': 'offers_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug')),
                ('type', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=50, verbose_name='النوع:')),
                ('image', models.FileField(blank=True, null=True, upload_to='profile', verbose_name='الصورة الشخصية :')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
                'db_table': 'profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegularBooking',
            fields=[
                ('regular_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=50)),
                ('arrival_date', models.DateTimeField(blank=True, null=True)),
                ('leave_date', models.DateTimeField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('count_persons', models.IntegerField(blank=True, null=True)),
                ('count_rooms', models.IntegerField(blank=True, null=True)),
                ('book_date', models.DateField(blank=True, null=True)),
                ('book_state', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'RegularBooking',
                'verbose_name_plural': 'RegularBookings',
                'db_table': 'regular_booking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('غرفة لفرد واحد', 'غرفة لفرد واحد'), ('غرفة لفردين', 'غرفة لفردين'), ('غرفة لفردين أو أكثر', 'غرفة لفردين أو أكثر'), ('غرفة لعائلة', 'غرفة لعائلة')], max_length=100)),
                ('room_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('photo', models.FileField(blank=True, null=True, upload_to='')),
                ('limit', models.IntegerField()),
                ('information', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resorts',
            fields=[
                ('resort_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='Resorts/name')),
                ('information', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Resort',
                'verbose_name_plural': 'Resorts',
                'db_table': 'resorts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('des_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('information', models.TextField(blank=True, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='Destinations/')),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'db_table': 'destinations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserauthsUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
                ('full_name', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(max_length=500)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, db_column='Nationality', max_length=100, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'userauths_user_pages',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CareDR',
            fields=[
                ('care', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.caretype')),
            ],
            options={
                'verbose_name': 'CareDR',
                'verbose_name_plural': 'CareDRS',
                'db_table': 'care_d_r',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DiseaseDR',
            fields=[
                ('disease', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.diseases')),
            ],
            options={
                'verbose_name': 'DiseaseDR',
                'verbose_name_plural': 'DiseaseDRS',
                'db_table': 'disease_d_r',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OffersBookingOffers',
            fields=[
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.offers')),
            ],
            options={
                'verbose_name': 'OffersBookingOffers',
                'verbose_name_plural': 'OffersBookingOffers',
                'db_table': 'offers_booking_offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegularRoom',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.rooms')),
            ],
            options={
                'verbose_name': 'RegularRoom',
                'verbose_name_plural': 'RegularRooms',
                'db_table': 'regular_room',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoomOffers',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.rooms')),
            ],
            options={
                'verbose_name': 'RoomOffer',
                'verbose_name_plural': 'RoomOffers',
                'db_table': 'room_offers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResortsPhone',
            fields=[
                ('resort', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='pages.resorts')),
                ('phone', models.CharField(max_length=12)),
            ],
            options={
                'verbose_name': 'ResortsPhone',
                'verbose_name_plural': 'ResortsPhone',
                'db_table': 'resorts_phone',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='resorts',
            name='des',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.destinations'),
        ),
    ]
